POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld0B5YWhvby5mciIsImlkIjo0LCJpYXQiOjE2OTQ3NjgwMDZ9.AXScjRNc2Z98Lk1Tj1_A6ChXnC4bX-JE5NsUFtzsK_k

{
    "author": "small",
    "url": "testo",
    "title": "test",
    "likes": 1,
    "year": 2023
}